# Generated by Django 4.1.1 on 2022-09-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_gest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gest',
        ),
    ]
