# Generated by Django 4.1.1 on 2022-09-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_gest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='firstname',
            new_name='fname',
        ),
    ]
