# Generated by Django 4.1.1 on 2022-09-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_firstname_pages_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='fname',
            new_name='firstname',
        ),
    ]
