# Generated by Django 4.1.1 on 2022-09-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_fname_pages_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Dept_name', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
