# Generated by Django 4.1.1 on 2022-09-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Product',
        ),
    ]
